AWSTemplateFormatVersion: '2010-09-09'
Description: EcoWeather Serverless Application (Lab Compatible)

Resources:

  WeatherTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: city
          AttributeType: S
      KeySchema:
        - AttributeName: city
          KeyType: HASH

  WeatherLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::891377078916:role/LabRole
      Timeout: 30
      Code:
        S3Bucket: ecoweather-code-siri
        S3Key: ecoweather.zip

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: ecoweather-api
      ProtocolType: HTTP

  HttpIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WeatherLambda.Arn}/invocations
      PayloadFormatVersion: "2.0"

  HttpRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "GET /weather"
      Target: !Sub integrations/${HttpIntegration}

  HttpStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: prod
      AutoDeploy: true

  ApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WeatherLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*

Outputs:
  ApiURL:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod/weather"
